# .github/workflows/ci-go.yml
name: Go CI

# Запускаем на пуш в main и на PR в main
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Проверка (Go ${{ matrix.go-version }})
    runs-on: ubuntu-latest
    env:
      # Принудительно включаем поддержку модулей
      GO111MODULE: 'on'
    strategy:
      matrix:
        # Версии Go для тестирования
        go-version: [ '1.21', '1.22' ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
          cache: 'gomod'

      - name: Go version
        run: go version

      - name: Download dependencies
        run: go mod download

      # 5) Сборка
      - name: Build
        run: go build ./...

      - name: Test with coverage
        run: |
          go test ./... -v -coverprofile=coverage.out
          go tool cover -func=coverage.out

      - name: Run linter
        run: |
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
          golangci-lint run --timeout=2m
